import type {
  CustomerEmailTemplate,
  CustomerEmailsBundle,
  EmailTemplateCategory,
  EmailTemplateId,
} from "@/lib/email/types";

const SITE = "https://salvyastore.com";

function tpl(
  id: EmailTemplateId,
  category: EmailTemplateCategory,
  name: string,
  description: string,
  trigger: string,
  subject: string,
  headline: string,
  body: string,
  ctaLabel: string,
  ctaUrl: string,
  opts?: { enabled?: boolean; previewText?: string; footerNote?: string },
): CustomerEmailTemplate {
  return {
    id,
    category,
    name,
    description,
    trigger,
    enabled: opts?.enabled !== false,
    subject,
    previewText: opts?.previewText ?? description.slice(0, 120),
    headline,
    body,
    ctaLabel,
    ctaUrl,
    footerNote:
      opts?.footerNote ?? "Questions? Reply to this email or contact {{support_email}}.",
  };
}

export const DEFAULT_EMAIL_TEMPLATES: Record<EmailTemplateId, CustomerEmailTemplate> = {
  order_confirmation: tpl(
    "order_confirmation",
    "order",
    "Order confirmed",
    "Immediate receipt after checkout — sets expectations like major fashion brands.",
    "Automation: order placed",
    "Your Salvya order {{order_number}} is confirmed",
    "Thanks, {{customer_name}} — we got your order",
    "We're preparing **{{product_title}}** for production. You'll receive updates when it moves to preparing, ships, and delivers.\n\nOrder total: **{{order_total}}** · Reference **{{order_number}}**",
    "Track your order",
    "{{track_order_url}}",
  ),
  order_preparing: tpl(
    "order_preparing",
    "order",
    "In production",
    "Your order is being prepared — reduces “where is my order?” support tickets.",
    "Automation: status → preparing",
    "We're making your Salvya order {{order_number}}",
    "Your piece is in production, {{customer_name}}",
    "**{{product_title}}** is now in our production queue. Quality checks and packing come next — we'll email you as soon as it ships.",
    "View order status",
    "{{track_order_url}}",
  ),
  order_shipped: tpl(
    "order_shipped",
    "order",
    "Shipped",
    "Carrier handoff with tracking — standard for DTC brands.",
    "Automation: status → shipped",
    "Your Salvya order {{order_number}} is on the way",
    "It's shipped, {{customer_name}}",
    "Your package left our warehouse.\n\nTracking: **{{tracking_number}}**\n\nDelivery timing depends on your region — tap below for live carrier updates.",
    "Track shipment",
    "{{tracking_url}}",
  ),
  order_delivered: tpl(
    "order_delivered",
    "order",
    "Delivered",
    "Delivery confirmation and soft upsell.",
    "Automation: status → delivered",
    "Delivered — enjoy your Salvya order {{order_number}}",
    "Delivered to your door",
    "We hope you love **{{product_title}}**. If anything isn't right, reply within 14 days and our team will help.",
    "Shop again",
    `${SITE}/shop`,
  ),
  order_cancelled: tpl(
    "order_cancelled",
    "order",
    "Order cancelled",
    "Clear cancellation notice with support path.",
    "Automation: status → cancelled",
    "Your Salvya order {{order_number}} was cancelled",
    "Order cancelled",
    "Hi {{customer_name}}, your order **{{order_number}}** for **{{product_title}}** has been cancelled.\n\nIf you were charged in error, refunds follow your payment method in 5–10 business days. Questions? Reply to this email.",
    "Contact support",
    "mailto:{{support_email}}",
  ),
  order_payment_failed: tpl(
    "order_payment_failed",
    "order",
    "Payment failed",
    "Recovery nudge when payment does not complete.",
    "Automation: payment status → failed",
    "Action needed — payment for {{order_number}}",
    "We couldn't process your payment",
    "Hi {{customer_name}}, payment for **{{product_title}}** ({{order_number}}) didn't go through.\n\nYou can try checkout again or use another method — your items may still be available for a limited time.",
    "Return to checkout",
    "{{cart_url}}",
  ),
  order_delay_notice: tpl(
    "order_delay_notice",
    "order",
    "Shipping delay",
    "Proactive transparency when production or carrier runs late.",
    "Manual: admin sends or future delay job",
    "A quick update on your Salvya order {{order_number}}",
    "Your order is taking a little longer",
    "Hi {{customer_name}}, **{{product_title}}** is still on the way — we're working with our partners to ship as soon as possible.\n\nWe appreciate your patience. You'll get tracking as soon as it leaves our facility.",
    "Track order",
    "{{track_order_url}}",
    { enabled: false },
  ),
  order_review_request: tpl(
    "order_review_request",
    "lifecycle",
    "Review request",
    "Post-delivery social proof ask — sent after delivered when enabled.",
    "Automation: after delivered (same update)",
    "How was your Salvya order {{order_number}}?",
    "We'd love your feedback, {{customer_name}}",
    "Your **{{product_title}}** should be with you now. A quick rating or photo helps other fans discover the drop.\n\nReply with feedback or tag us — it means a lot to the artist community.",
    "Shop new drops",
    `${SITE}/shop`,
    { enabled: true },
  ),
  welcome_account: tpl(
    "welcome_account",
    "lifecycle",
    "Welcome",
    "First impression after signup — onboards like premium streetwear brands.",
    "Automation: user registered",
    "Welcome to Salvya, {{customer_name}}",
    "You're in — welcome to Salvya",
    "Your account is ready. Follow artists, save your bag, and get order updates in one place.\n\nNew drops land first on the feed — don't miss the next release.",
    "Explore the shop",
    `${SITE}/shop`,
  ),
  profile_complete_nudge: tpl(
    "profile_complete_nudge",
    "lifecycle",
    "Complete your profile",
    "Nudge to add name, size preferences, and shipping — improves conversion.",
    "Automation: profile incomplete (API / cron)",
    "{{customer_name}}, finish setting up your Salvya account",
    "One step left",
    "Add your details so checkout is faster and we can recommend the right sizes for **{{product_title}}** and future drops.",
    "Complete profile",
    `${SITE}/account/profile`,
    { enabled: false },
  ),
  cart_abandoned: tpl(
    "cart_abandoned",
    "lifecycle",
    "Abandoned cart (1h)",
    "First recovery email — high ROI automation.",
    "Automation: cart abandoned (~1 hour)",
    "You left something in your bag",
    "Still thinking it over, {{customer_name}}?",
    "Your **{{product_title}}** is still reserved in your bag. Checkout before it sells out — streetwear drops move fast.",
    "Complete checkout",
    "{{cart_url}}",
  ),
  cart_reminder_final: tpl(
    "cart_reminder_final",
    "lifecycle",
    "Abandoned cart (24h)",
    "Final reminder with optional urgency.",
    "Automation: cart abandoned (~24 hours)",
    "Last chance — your Salvya bag",
    "Your bag expires soon",
    "Hi {{customer_name}}, this is a friendly final reminder about **{{product_title}}** in your bag.\n\nUse code **{{discount_code}}** if applicable — or checkout now to secure your size.",
    "Return to bag",
    "{{cart_url}}",
    { enabled: false },
  ),
  restock_interest: tpl(
    "restock_interest",
    "lifecycle",
    "Back in stock",
    "Notify waitlist when SKU returns.",
    "Automation: restock signup",
    "Back in stock — {{product_title}}",
    "It's back, {{customer_name}}",
    "**{{product_title}}** is available again in limited quantities. Waitlist members get first access — grab your size before it's gone.",
    "Shop now",
    "{{cart_url}}",
  ),
  post_purchase_cross_sell: tpl(
    "post_purchase_cross_sell",
    "lifecycle",
    "Cross-sell",
    "Complementary pieces after purchase — like Amazon “frequently bought together”.",
    "Automation: after delivered (optional, off by default)",
    "Complete the look, {{customer_name}}",
    "Pairs well with your order",
    "Fans who bought **{{product_title}}** also love pieces from **{{artist_name}}**. Explore the latest from the same drop.",
    "See recommendations",
    `${SITE}/shop`,
    { enabled: false },
  ),
  account_security_alert: tpl(
    "account_security_alert",
    "account",
    "Security alert",
    "New sign-in or password change notice.",
    "Automation: security event (API)",
    "Security notice for your Salvya account",
    "Did you make this change?",
    "Hi {{customer_name}}, we noticed activity on your Salvya account. If this was you, no action is needed.\n\nIf not, reset your password and contact {{support_email}} immediately.",
    "Secure my account",
    `${SITE}/login`,
    { enabled: false },
  ),
  password_reset_info: tpl(
    "password_reset_info",
    "account",
    "Password reset (info)",
    "Companion to Supabase auth email — branded reassurance.",
    "Reference — Supabase sends the link",
    "Reset your Salvya password",
    "Password reset requested",
    "If you requested a reset, check your inbox for a secure link from our auth system.\n\nDidn't request this? Ignore this message — your password stays the same.",
    "Sign in",
    `${SITE}/login`,
    { enabled: false },
  ),
  new_collection: tpl(
    "new_collection",
    "marketing",
    "New collection launch",
    "Hero campaign for a full collection drop.",
    "Manual: admin broadcast",
    "New drop — {{collection_name}} is live",
    "{{collection_name}} just dropped",
    "Hi {{customer_name}}, **{{collection_name}}** is live on Salvya — limited pieces from **{{artist_name}}**.\n\nEarly access ends soon. Tap below to shop the full lookbook.",
    "Shop the collection",
    `${SITE}/shop`,
  ),
  seasonal_sale: tpl(
    "seasonal_sale",
    "marketing",
    "Seasonal sale",
    "Site-wide or seasonal promotion.",
    "Manual: admin broadcast",
    "Season sale — up to 30% off select Salvya",
    "Our seasonal sale is on",
    "Hi {{customer_name}}, for a short time, selected pieces are on sale across the store.\n\nUse **{{discount_code}}** at checkout while inventory lasts.",
    "Shop the sale",
    `${SITE}/shop`,
  ),
  vip_early_access: tpl(
    "vip_early_access",
    "marketing",
    "VIP early access",
    "Reward repeat customers before public launch.",
    "Manual: admin broadcast",
    "You're invited — early access to {{collection_name}}",
    "VIP early access, {{customer_name}}",
    "You're on our priority list. Shop **{{collection_name}}** before the public drop opens.\n\nYour link is unique to this inbox — please don't forward.",
    "Shop early access",
    `${SITE}/shop`,
  ),
  flash_sale: tpl(
    "flash_sale",
    "marketing",
    "Flash sale (24h)",
    "Urgency-driven short window promo.",
    "Manual: admin broadcast",
    "24-hour flash — {{discount_code}} inside",
    "Flash sale ends tonight",
    "Hi {{customer_name}}, for the next 24 hours, use **{{discount_code}}** on select Salvya pieces.\n\nWhen the timer ends, prices go back to full.",
    "Shop flash sale",
    `${SITE}/shop`,
  ),
  win_back: tpl(
    "win_back",
    "marketing",
    "Win-back inactive",
    "Re-engage customers with no order in 90+ days.",
    "Automation: inactive 90d (cron / future)",
    "We miss you, {{customer_name}}",
    "Come back to Salvya",
    "It's been a while since your last order. New artist drops and restocks landed — here's **{{discount_code}}** if you'd like to return.",
    "See what's new",
    `${SITE}/shop`,
    { enabled: false },
  ),
  newsletter_welcome: tpl(
    "newsletter_welcome",
    "marketing",
    "Newsletter welcome",
    "Double opt-in welcome for marketing list.",
    "Automation: marketing opt-in at signup",
    "You're on the Salvya list",
    "Thanks for subscribing",
    "Hi {{customer_name}}, you'll get drops, restocks, and exclusive offers from Salvya and our artists.\n\nManage preferences anytime.",
    "Browse latest",
    `${SITE}/shop`,
    { enabled: false },
  ),
  artist_drop_alert: tpl(
    "artist_drop_alert",
    "marketing",
    "Artist drop alert",
    "Notify followers when an artist releases.",
    "Manual: admin broadcast / future artist follow",
    "New from {{artist_name}} — out now",
    "{{artist_name}} just dropped",
    "Hi {{customer_name}}, **{{artist_name}}** released new pieces on Salvya. Limited run — shop the drop before sizes sell out.",
    "View drop",
    `${SITE}/shop`,
  ),
  free_shipping_promo: tpl(
    "free_shipping_promo",
    "marketing",
    "Free shipping weekend",
    "Shipping promo to lift conversion.",
    "Manual: admin broadcast",
    "Free shipping this weekend on Salvya",
    "Free shipping — this weekend only",
    "Hi {{customer_name}}, enjoy free shipping on qualifying orders through Sunday.\n\nNo code needed — discount applies at checkout automatically where eligible.",
    "Start shopping",
    `${SITE}/shop`,
  ),
};

export const DEFAULT_CUSTOMER_EMAILS: CustomerEmailsBundle = {
  global: {
    emailsEnabled: true,
    fromName: "Salvya Team",
    fromEmail: "hello@salvyastore.com",
    replyTo: "support@salvyastore.com",
    supportEmail: "support@salvyastore.com",
    brandAccent: "#2D6BFF",
  },
  templates: DEFAULT_EMAIL_TEMPLATES,
};

export const EMAIL_TEMPLATE_IDS = Object.keys(DEFAULT_EMAIL_TEMPLATES) as EmailTemplateId[];
