/** @deprecated Import from `@/lib/help-center` — kept for backward compatibility. */
export {
  HELP_CENTER_PATH,
  HELP_RECENTS_STORAGE_KEY,
  HELP_FEATURED_IDS,
  HELP_SECTION_META,
  HELP_TOPICS,
  HELP_FAQS,
  HELP_SUGGESTED_QUERIES,
  HELP_TRENDING_SEARCHES,
  HELP_POPULAR_ACTIONS,
  HELP_KB_CATEGORIES,
  HELP_AI_ARTICLES,
  HELP_DEV_ENDPOINTS,
  HELP_PLATFORM_FLOWS,
  HELP_PLATFORM_INDEX,
  HELP_SCHEMA_TYPES,
  HELP_TAB_META,
  HELP_TAB_SECTIONS,
  SECTION_ORDER,
  filterHelpTopics,
  filterFaqs,
  getFeaturedTopics,
  getTopicsByIds,
  type HelpTopic,
  type HelpFaq,
  type HelpSection,
  type HelpTabId,
} from "@/lib/help-center";
