import type { HelpFaq, HelpSection, HelpTopic } from "@/lib/help-center/types";

export const HELP_RECENTS_STORAGE_KEY = "salvya-help-search-recents-v2";

export const HELP_FEATURED_IDS: string[] = [
  "track",
  "returns",
  "bag",
  "recovery",
  "shipping",
  "sizes",
  "login",
  "creator-apply",
  "dev-portal",
  "help-ai-overview",
];

export const HELP_SECTION_META: Record<HelpSection, { title: string; subtitle: string }> = {
  orders: { title: "Shopping & orders", subtitle: "Bag, tracking, sizing, and delivery" },
  account: { title: "Account & security", subtitle: "Sign-in, recovery, and profile" },
  legal: { title: "Legal & policies", subtitle: "Terms, shipping, payments, cookies, returns" },
  creators: { title: "Creators", subtitle: "Programme, workspace, payouts, and links" },
  platform: { title: "Platform", subtitle: "How Salvya works, trust, and navigation" },
  developers: { title: "Developers", subtitle: "APIs, auth, SDKs, and integrations" },
  ai: { title: "AI & search", subtitle: "Machine-readable platform knowledge" },
  api: { title: "API reference", subtitle: "REST endpoints and webhooks" },
};

export const HELP_TOPICS: HelpTopic[] = [
  { id: "shop-home", section: "orders", category: "shopping", badge: "Shop", title: "Shop home", blurb: "Browse artists, drops, and official merch.", href: "/shop", keywords: ["home", "browse", "catalog", "merch", "drops"] },
  { id: "bag", section: "orders", category: "shopping", badge: "Bag", title: "Your bag", blurb: "Synced cart lines when signed in; guest copy on this browser.", href: "/preview-bag", keywords: ["cart", "checkout", "items", "order", "empty", "device"] },
  { id: "track", section: "orders", category: "shopping", badge: "Tracking", title: "Track an order", blurb: "Look up SVY status with order number and email.", href: "/track-order", keywords: ["tracking", "delivery", "parcel", "status", "where"] },
  { id: "sizes", section: "orders", category: "shopping", badge: "Fit", title: "Size guide", blurb: "Measurements and fit notes before you pick a size.", href: "/size-guide", keywords: ["fit", "measure", "chart", "s", "m", "l", "xl"] },
  { id: "about", section: "platform", category: "platform", badge: "Salvya", title: "Our story & team", blurb: "Who we are and how we work with artists.", href: "/about", keywords: ["about", "mission", "team", "story"] },
  { id: "menu", section: "platform", category: "platform", badge: "Menu", title: "App menu & navigation", blurb: "Policies, account, and creator tools in one hub.", href: "/menu", keywords: ["menu", "navigation", "policies", "hub"] },
  { id: "help-faq", section: "platform", category: "platform", badge: "FAQ", title: "Frequently asked questions", blurb: "Searchable answers for orders, creators, developers, and payments.", href: "/faq", keywords: ["faq", "questions", "answers", "help"] },
  { id: "help-ai-overview", section: "ai", category: "platform", badge: "AI", title: "How Salvya works (AI overview)", blurb: "Platform summary for search engines and AI crawlers.", href: "/help-center#ai-seo", keywords: ["ai", "overview", "architecture", "crawler", "llms"] },
  { id: "help-trust", section: "platform", category: "platform", badge: "Trust", title: "Trust & safety", blurb: "Fraud prevention, moderation, and payout integrity.", href: "/terms", keywords: ["trust", "safety", "fraud", "moderation"] },
  { id: "help-search", section: "platform", category: "platform", badge: "Discover", title: "Search & recommendations", blurb: "Find products, artists, and trending drops.", href: "/search", keywords: ["search", "discover", "trending", "recommendations"] },
  { id: "help-notifications", section: "platform", category: "platform", badge: "Alerts", title: "Notifications", blurb: "Order updates and account alerts when signed in.", href: "/notifications", keywords: ["notifications", "alerts", "email", "push"] },
  { id: "shipping", section: "legal", category: "shopping", badge: "Delivery", title: "Shipping & delivery", blurb: "Regions, timelines, partners, and expectations.", href: "/shipping", keywords: ["ship", "eu", "international", "carrier", "delay"] },
  { id: "returns", section: "legal", category: "shopping", badge: "Returns", title: "Returns & refunds", blurb: "Windows, condition rules, and refund timing.", href: "/returns", keywords: ["refund", "exchange", "send back", "money"] },
  { id: "payment", section: "legal", category: "shopping", badge: "Pay", title: "Payment methods", blurb: "Cards, PayPal, COD where offered.", href: "/payment", keywords: ["card", "paypal", "apple pay", "invoice", "declined"] },
  { id: "terms", section: "legal", category: "legal", badge: "Legal", title: "Terms of Service", blurb: "Rules for using Salvya and buying merch.", href: "/terms", keywords: ["terms", "conditions", "agreement", "rules"] },
  { id: "terms-account", section: "legal", category: "legal", badge: "Account", title: "Account terms", blurb: "Eligibility, responsibilities, lifecycle.", href: "/terms/account", keywords: ["profile", "close account", "suspend"] },
  { id: "terms-influencer", section: "legal", category: "legal", badge: "Programme", title: "Creator programme terms", blurb: "DH commissions, payouts, and policies.", href: "/terms/creator", keywords: ["affiliate", "creator", "commission", "payout"] },
  { id: "cookies", section: "legal", category: "legal", badge: "Privacy", title: "Cookies policy", blurb: "How Salvya uses cookies and similar tech.", href: "/cookies", keywords: ["gdpr", "consent", "analytics", "pixels"] },
  { id: "cookies-settings", section: "legal", category: "legal", badge: "Privacy", title: "Cookie settings", blurb: "Update non-essential cookie preferences.", href: "/cookies/settings", keywords: ["preferences", "opt out", "toggle"] },
  { id: "contact", section: "legal", category: "legal", badge: "Support", title: "Contact us", blurb: "Reach Salvya support for orders and account help.", href: "/contact", keywords: ["contact", "support", "email", "help"] },
  { id: "report-problem", section: "legal", category: "legal", badge: "Report", title: "Report a problem", blurb: "Submit bugs, abuse, or checkout issues.", href: "/report-problem", keywords: ["report", "bug", "abuse", "issue"] },
  { id: "recovery", section: "account", category: "account-security", badge: "Access", title: "Sign-in & account help", blurb: "Recovery, device limits, lockouts.", href: "/terms#recovery", keywords: ["password", "login", "locked", "2fa", "email", "reset"] },
  { id: "login", section: "account", category: "account-security", badge: "Access", title: "Sign in", blurb: "Access orders, bag sync, and creator tools.", href: "/login", keywords: ["log in", "session", "auth"] },
  { id: "register", section: "account", category: "account-security", badge: "Join", title: "Create account", blurb: "Open a Salvya account in a few steps.", href: "/register", keywords: ["sign up", "new user", "join"] },
  { id: "forgot-password", section: "account", category: "account-security", badge: "Reset", title: "Forgot password", blurb: "Secure password reset via email.", href: "/forgot-password", keywords: ["forgot", "reset", "password", "recovery"] },
  { id: "update-password", section: "account", category: "account-security", badge: "Security", title: "Update password", blurb: "Change password when signed in.", href: "/update-password", keywords: ["password", "change", "security"] },
  { id: "account", section: "account", category: "account-security", badge: "Profile", title: "Your account", blurb: "Addresses, preferences, order history.", href: "/account/profile", keywords: ["profile", "settings", "orders"] },
  { id: "creator-home", section: "creators", category: "creators", badge: "Creators", title: "Creator programme", blurb: "Earn fixed DH per item sold by follower band.", href: "/creator", keywords: ["sell", "creator", "commission", "followers", "DH"] },
  { id: "creator-apply", section: "creators", category: "creators", badge: "Apply", title: "Apply to sell", blurb: "Submit your creator application.", href: "/creator/apply", keywords: ["application", "onboard", "approval"] },
  { id: "creator-dashboard", section: "creators", category: "creators", badge: "Workspace", title: "Creator dashboard", blurb: "Stats, earnings, and activity overview.", href: "/creator/dashboard", keywords: ["dashboard", "analytics", "stats"] },
  { id: "creator-rewards", section: "creators", category: "creators", badge: "Links", title: "Promo links", blurb: "Trackable links and click performance.", href: "/creator/links", keywords: ["links", "promo", "track", "utm"] },
  { id: "creator-wallet", section: "creators", category: "creators", badge: "Payouts", title: "Wallet & payouts", blurb: "Balance, commission band, withdrawal requests.", href: "/creator/wallet", keywords: ["wallet", "payout", "balance", "withdraw", "DH"] },
  { id: "creator-analytics", section: "creators", category: "creators", badge: "Stats", title: "Creator analytics", blurb: "Conversion, clicks, and link performance.", href: "/creator/analytics", keywords: ["analytics", "conversion", "ctr", "performance"] },
  { id: "creator-terms", section: "creators", category: "creators", badge: "Legal", title: "Creator terms", blurb: "Programme rules and commission tiers.", href: "/terms/creator", keywords: ["terms", "legal", "commission"] },
  { id: "creator-notifications", section: "creators", category: "creators", badge: "Alerts", title: "Creator notifications", blurb: "Orders, payouts, and workspace alerts.", href: "/creator/notifications", keywords: ["notifications", "alerts", "orders"] },
  { id: "dev-portal", section: "developers", category: "developers", badge: "Dev", title: "Developer portal", blurb: "API overview, auth, SDKs, and examples.", href: "/developers", keywords: ["developer", "api", "sdk", "docs"] },
  { id: "dev-auth", section: "developers", category: "developers", badge: "Auth", title: "Authentication", blurb: "Supabase session cookies and `/api/auth/me`.", href: "/developers#auth", keywords: ["auth", "session", "token", "oauth"] },
  { id: "dev-orders-api", section: "api", category: "developers", badge: "API", title: "Orders API", blurb: "Place and list customer orders.", href: "/developers#orders-api", keywords: ["orders", "api", "rest", "checkout"] },
  { id: "dev-products-api", section: "api", category: "developers", badge: "API", title: "Products & catalog", blurb: "Storefront catalog and discovery endpoints.", href: "/developers#products-api", keywords: ["products", "catalog", "shop", "api"] },
  { id: "dev-creators-api", section: "api", category: "developers", badge: "API", title: "Creators API", blurb: "Stats, wallet, links, and analytics.", href: "/developers#creators-api", keywords: ["creator", "api", "analytics", "wallet"] },
  { id: "dev-webhooks", section: "developers", category: "developers", badge: "Hooks", title: "Webhooks", blurb: "Payment and order lifecycle events for integrations.", href: "/developers#webhooks", keywords: ["webhook", "events", "payment", "integration"] },
  { id: "openapi-spec", section: "api", category: "developers", badge: "OpenAPI", title: "OpenAPI specification", blurb: "Download machine-readable API spec.", href: "/openapi.json", keywords: ["openapi", "swagger", "spec", "json"] },
  { id: "llms-txt", section: "ai", category: "platform", badge: "AI", title: "LLMs.txt", blurb: "AI crawler discovery file.", href: "/llms.txt", keywords: ["llms", "ai", "crawler", "gpt", "gemini"] },
  { id: "sitemap-xml", section: "ai", category: "platform", badge: "SEO", title: "XML sitemap", blurb: "Public URL index for search engines.", href: "/sitemap.xml", keywords: ["sitemap", "seo", "crawl", "google"] },
];

export const HELP_FAQS: HelpFaq[] = [
  {
    id: "where-order",
    group: "customer",
    question: "Where is my order?",
    answer: "Open Track an order with your SVY reference and checkout email. Signed-in orders also appear under Account.",
    links: [{ href: "/track-order", label: "Track an order" }, { href: "/preview-bag", label: "Your bag" }],
  },
  {
    id: "returns-window",
    group: "customer",
    question: "How do returns and refunds work?",
    answer: "Returns & refunds explains time windows, condition requirements, and refund timing.",
    links: [{ href: "/returns", label: "Returns policy" }],
  },
  {
    id: "locked-out",
    group: "customer",
    question: "I cannot sign in — what should I do?",
    answer: "Use account recovery documentation and forgot password for secure reset.",
    links: [{ href: "/terms#recovery", label: "Sign-in help" }, { href: "/forgot-password", label: "Forgot password" }],
  },
  {
    id: "bag-empty-signed-in",
    group: "customer",
    question: "I signed in but my bag looks empty.",
    answer: "Guest bag lines merge into your account on sign-in when sync is available. Check the device where items were added.",
    links: [{ href: "/preview-bag", label: "Open your bag" }],
  },
  {
    id: "creator-payout-dh",
    group: "creator",
    question: "How much do creators earn per sale?",
    answer: "Salvya pays fixed DH (MAD) per qualifying item based on Instagram follower bands declared at application — from 7 DH to 25 DH per item.",
    links: [{ href: "/terms/creator", label: "Creator terms" }, { href: "/creator/wallet", label: "Wallet & band" }],
  },
  {
    id: "creator-approval",
    group: "creator",
    question: "How long does creator approval take?",
    answer: "Applications are reviewed manually. Typical review is 2–4 business days. You can shop while pending.",
    links: [{ href: "/creator/apply", label: "Application status" }],
  },
  {
    id: "api-auth",
    group: "developer",
    question: "How do I authenticate with the Salvya API?",
    answer: "Customer and creator endpoints use Supabase session cookies from sign-in. Keep credentials secure and never share session tokens.",
    links: [{ href: "/developers#auth", label: "Developer auth" }, { href: "/api/auth/me", label: "Session probe" }],
  },
  {
    id: "api-rate-limits",
    group: "developer",
    question: "Are there API rate limits?",
    answer: "Public storefront endpoints are cached and rate-limited at the edge. Creator APIs require an authenticated creator session and may throttle abusive patterns.",
    links: [{ href: "/developers", label: "Developer portal" }],
  },
  {
    id: "ai-crawl",
    group: "ai",
    question: "How can AI systems understand Salvya?",
    answer: "Use Help Center AI & SEO section, llms.txt, structured data on PDPs, and public policy pages. All major routes are in sitemap.xml.",
    links: [{ href: "/llms.txt", label: "LLMs.txt" }, { href: "/faq", label: "FAQ" }, { href: "/help-center#ai-seo", label: "AI overview" }],
  },
  {
    id: "payment-failed",
    group: "payment",
    question: "My payment failed at checkout — am I charged?",
    answer: "Failed authorizations are not captured. Retry checkout or use another method listed on Payment methods.",
    links: [{ href: "/payment", label: "Payment methods" }, { href: "/contact", label: "Contact support" }],
  },
  {
    id: "privacy-cookies",
    group: "customer",
    question: "How do I change cookie or privacy choices?",
    answer: "Read the cookies policy, then open Cookie settings to toggle non-essential categories.",
    links: [{ href: "/cookies", label: "Cookies policy" }, { href: "/cookies/settings", label: "Cookie settings" }],
  },
  {
    id: "cancel-order",
    group: "customer",
    question: "Can I cancel my order after checkout?",
    answer:
      "You may cancel within twelve (12) hours of placing the order while production has not started. After that window, items are made on demand and cancellation is not available except where the Returns policy applies.",
    links: [{ href: "/returns", label: "Returns policy" }, { href: "/contact", label: "Contact support" }],
  },
  {
    id: "production-start",
    group: "customer",
    question: "When does production start on my order?",
    answer:
      "Production typically begins after payment verification and the cancellation window closes. Track your order for fulfillment and shipment updates.",
    links: [{ href: "/track-order", label: "Track order" }, { href: "/shipping", label: "Shipping policy" }],
  },
  {
    id: "official-merch",
    group: "customer",
    question: "Is Salvya merch official artist merchandise?",
    answer:
      "Salvya partners with artists for official, limited drops and on-demand production. Each product page shows the artist and listing details before checkout.",
    links: [{ href: "/about", label: "About Salvya" }, { href: "/shop", label: "Shop" }],
  },
  {
    id: "international-shipping",
    group: "customer",
    question: "Do you ship internationally?",
    answer: "Shipping regions, carriers, and timelines depend on your delivery address. See Shipping & delivery for current coverage and estimates.",
    links: [{ href: "/shipping", label: "Shipping policy" }, { href: "/size-guide", label: "Size guide" }],
  },
  {
    id: "creator-attribution",
    group: "creator",
    question: "How does creator attribution work on orders?",
    answer:
      "Promo links and tracking codes attribute qualifying sales to your creator account. Self-referral and fraud patterns are blocked per programme rules.",
    links: [{ href: "/creator/links", label: "Promo links" }, { href: "/terms/creator", label: "Creator terms" }],
  },
  {
    id: "creator-payout-timing",
    group: "creator",
    question: "When do creator payouts arrive?",
    answer:
      "Earnings accrue on qualifying attributed orders. Withdrawal timing depends on your wallet balance, verification status, and payout method in the creator workspace.",
    links: [{ href: "/creator/wallet", label: "Wallet & payouts" }, { href: "/terms/creator", label: "Creator terms" }],
  },
  {
    id: "openapi-download",
    group: "developer",
    question: "Where is the OpenAPI specification?",
    answer: "Download the machine-readable spec at /openapi.json or browse grouped endpoints in the Developer portal.",
    links: [{ href: "/openapi.json", label: "OpenAPI JSON" }, { href: "/developers", label: "Developer portal" }],
  },
  {
    id: "support-response",
    group: "customer",
    question: "How fast does support respond?",
    answer:
      "We aim to reply to order and account enquiries within one to two business days. Include your SVY order reference when contacting us about a purchase.",
    links: [{ href: "/contact", label: "Contact support" }, { href: "/report-problem", label: "Report a problem" }],
  },
];

export const SECTION_ORDER: HelpSection[] = [
  "orders",
  "account",
  "creators",
  "platform",
  "developers",
  "api",
  "legal",
  "ai",
];
