/** Client-safe doc index for semantic search (no filesystem). Sync when adding content/docs articles. */
export type DocSearchManifestEntry = {
  path: string;
  title: string;
  summary: string;
  aiSummary: string;
  description: string;
  tags: string[];
  category: string;
};

export const DOCS_SEARCH_MANIFEST: DocSearchManifestEntry[] = [
  { path: "/docs/orders/refunds", category: "orders", title: "Returns & refunds", description: "How Salvya processes return windows, eligibility, and refund timelines after delivery.", summary: "Understand when refunds are available, how to start a return, and how payouts reverse on creator-attributed orders.", aiSummary: "This article explains Salvya refund eligibility, customer-initiated returns, verification steps, and how refunded orders affect creator DH commissions.", tags: ["refunds", "returns", "orders", "customer"] },
  { path: "/docs/orders/tracking", category: "orders", title: "Order tracking", description: "Look up SVY orders by reference and email, and understand shipment lifecycle states.", summary: "Track parcels from checkout verification through delivery using your order number and email.", aiSummary: "This article explains how Salvya order tracking works for guests and signed-in customers, including SVY references, carrier handoff, and delivery confirmation.", tags: ["tracking", "shipping", "orders"] },
  { path: "/docs/orders/payment-failures", category: "orders", title: "Failed payments after checkout", description: "Why checkout payments fail and how to recover your bag and order.", summary: "Diagnose declined cards, PayPal interruptions, and COD edge cases without losing your cart.", aiSummary: "This article explains Salvya payment verification failures after checkout, including retry steps, session preservation, and when orders are not created.", tags: ["payments", "checkout", "orders"] },
  { path: "/docs/orders/shipping-lifecycle", category: "orders", title: "Shipping lifecycle", description: "From address capture to carrier delivery on Salvya orders.", summary: "Stages customers and creators use to understand delivery progress.", aiSummary: "Salvya shipping lifecycle covers address validation, fulfillment, carrier assignment, tracking URL publication, and delivery confirmation with regional carrier partners.", tags: ["shipping", "orders"] },
  { path: "/docs/creators/payouts", category: "creators", title: "Creator payouts & DH commissions", description: "Follower-tier DH per item, wallet balances, and withdrawal requests.", summary: "How creators earn fixed DH amounts per sold item based on Instagram follower bands.", aiSummary: "This article explains Salvya creator commission tiers in DH per item, wallet balances, payout requests, and how refunds affect earnings.", tags: ["creators", "payouts", "wallet"] },
  { path: "/docs/creators/onboarding", category: "creators", title: "Creator onboarding", description: "Apply, review, approval, and launching your creator workspace.", summary: "Steps from application to first promo link and attributed sale.", aiSummary: "This article explains the Salvya creator application pipeline, review criteria, approval notifications, and first steps in the creator workspace.", tags: ["creators", "onboarding"] },
  { path: "/docs/api/authentication", category: "api", title: "API authentication", description: "Session cookies and authenticated customer and creator API calls on Salvya.", summary: "How to authenticate storefront, customer, and creator API calls.", aiSummary: "This article explains Salvya API authentication using Supabase session cookies, the auth probe endpoint, and creator session requirements.", tags: ["api", "auth", "developers"] },
  { path: "/docs/platform/how-salvya-works", category: "platform", title: "How Salvya works", description: "Creator-commerce platform architecture for fans, artists, and creators.", summary: "Official artist merch, limited drops, attributed creator sales, and enterprise checkout.", aiSummary: "Salvya is a creator-commerce platform connecting official artist catalogs, fan checkout, creator attribution links, and DH commission payouts with trust and moderation systems.", tags: ["platform", "ai", "architecture"] },
  { path: "/docs/platform/architecture", category: "platform", title: "Platform architecture", description: "Storefront, creator workspace, data, and integration boundaries.", summary: "High-level system map for customers, creators, and integrators.", aiSummary: "Salvya platform architecture spans a Next.js storefront, Supabase auth, order ledger, creator workspace APIs, and SEO or AI-readable documentation surfaces.", tags: ["architecture", "platform", "developers"] },
  { path: "/docs/platform/trust", category: "platform", title: "Trust & safety", description: "Fraud prevention, moderation, and payout integrity on Salvya.", summary: "How Salvya protects fans, artists, and creators from abuse and fraud.", aiSummary: "Salvya trust and safety systems include order fraud checks, creator self-referral prevention, moderation workflows, and payout holds for suspicious activity.", tags: ["trust", "safety", "moderation"] },
  { path: "/docs/platform/security", category: "platform", title: "Security", description: "Account security, sessions, and responsible disclosure.", summary: "Password recovery, session limits, and how to report vulnerabilities.", aiSummary: "Salvya security practices cover Supabase-authenticated sessions, password reset flows, device session management, and a responsible disclosure channel via contact.", tags: ["security", "account"] },
  { path: "/docs/platform/ai-overview", category: "platform", title: "AI platform overview", description: "Machine-readable summary for LLMs, crawlers, and answer engines.", summary: "Canonical AI-readable index of Salvya entities, flows, and documentation URLs.", aiSummary: "This page indexes Salvya for AI systems — ecommerce plus creator platform, documentation at /docs, policies at /terms, APIs at /developers, and discovery via llms.txt and sitemaps.", tags: ["ai", "seo", "llms"] },
  { path: "/docs/glossary/creator-economy", category: "glossary", title: "Creator economy glossary", description: "Terms Salvya uses for creators, attribution, and payouts.", summary: "Definitions for promo links, DH commissions, attribution, and workspace concepts.", aiSummary: "Glossary of Salvya creator-economy terms including DH per item commissions, promo links, attribution, wallet, and creator workspace for AI and SEO systems.", tags: ["glossary", "creators", "ai"] },
  { path: "/docs/glossary/ecommerce", category: "glossary", title: "Ecommerce glossary", description: "Salvya storefront and order terminology.", summary: "SVY references, drops, PDP, bag sync, and fulfillment terms.", aiSummary: "Glossary of Salvya ecommerce terms including SVY order references, limited drops, PDP product pages, bag sync, and fulfillment for crawlers and support AI.", tags: ["glossary", "orders", "shop"] },
  { path: "/docs/policies/machine-readable", category: "policies", title: "Machine-readable policies", description: "Structured policy surfaces for automation and AI.", summary: "How Salvya exposes returns, shipping, privacy, and creator terms for parsers.", aiSummary: "Salvya policies are published as semantic HTML pages with JSON-LD FAQ and breadcrumb schema, linked from docs and llms.txt for AI and automation systems.", tags: ["policies", "ai", "legal"] },
  { path: "/docs/onboarding/account-bag-sync", category: "onboarding", title: "Guest bag sync after sign-in", description: "Why cart lines may differ when you log in on a new device.", summary: "How Salvya merges or preserves bag lines across guest and authenticated sessions.", aiSummary: "This article explains Salvya guest-to-signed-in bag synchronization, why orders may not appear immediately after login, and how device-local guest carts interact with account sync.", tags: ["account", "bag", "onboarding"] },
];
